import React from 'react';
import { useLocation, Link } from 'react-router-dom';
import '../styles/BookingConfirmed.css'; // Specific CSS for BookingConfirmed

function BookingConfirmed() {
  const location = useLocation();
  const { selectedSkills, selectedDate, selectedTime, estimatedDuration } = location.state || {};

  const bookingId = "SBY8B3EOLUH"; // Static for now, typically generated by backend

  const displayDate = selectedDate ? new Date(selectedDate).toLocaleDateString('en-US', {
    weekday: 'short', month: 'short', day: 'numeric', year: 'numeric'
  }) : 'N/A';

  return (
    <div className="booking-confirmed-page">
      <Link to="/" className="back-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="feather feather-arrow-left">
          <line x1="19" y1="12" x2="5" y2="12"></line>
          <polyline points="12 19 5 12 12 5"></polyline>
        </svg> Back to Home
      </Link>
      <h2 className="page-title">Booking Confirmed!</h2>
      <p className="page-description">Your skill assessment has been successfully scheduled.</p>

      <div className="card booking-details-card">
        <h3>Booking Details</h3>
        <div className="details-grid">
          <div className="detail-item">
            <strong>Booking ID</strong>
            <span>{bookingId}</span>
          </div>
          <div className="detail-item">
            <strong>Test Date</strong>
            <span>{displayDate}</span>
          </div>
          <div className="detail-item">
            <strong>Test Time</strong>
            <span>{selectedTime}</span>
          </div>
          <div className="detail-item">
            <strong>Duration</strong>
            <span>~{estimatedDuration} minutes</span>
          </div>
        </div>
        <div className="selected-skills-section">
          <strong>Selected Skills ({selectedSkills ? selectedSkills.length : 0})</strong>
          <div className="skill-tags-container">
            {selectedSkills && selectedSkills.length > 0 ? (
              selectedSkills.map(skill => (
                <span key={skill} className="skill-tag">{skill}</span>
              ))
            ) : (
              <span>No skills selected.</span>
            )}
          </div>
        </div>
      </div>

      <div className="card what-next-card">
        <h3>What's Next?</h3>
        <div className="next-steps-list">
          <div className="step-item">
            <span className="step-number">1</span>
            <div className="step-content">
              <strong>Test Link Email</strong>
              <p>You will receive your personalized test link via email within 24 hours.</p>
            </div>
          </div>
          <div className="step-item">
            <span className="step-number">2</span>
            <div className="step-content">
              <strong>Take Your Test</strong>
              <p>Click the link in your email at the scheduled time to begin your assessment.</p>
            </div>
          </div>
          <div className="step-item">
            <span className="step-number">3</span>
            <div className="step-content">
              <strong>Get Results</strong>
              <p>Receive your detailed results and recommendations within 2-3 hours after completion.</p>
            </div>
          </div>
        </div>
        <p className="important-note">
          <strong>Important:</strong> Your test link will be emailed to you within 24 hours. Please check your inbox and spam folder.
        </p>
      </div>
    </div>
  );
}

export default BookingConfirmed;